### PR TITLE
Fixed screenshots on systems with multiple displays

### PR DESCRIPTION
**Pull request by s1hofmann**
This PR fixes the wrong calculation of screenshot regions in multi monitor setups

### CODE REVIEW

**Comment by DaAitch** [comment]
awesome I will check it, :laughing: it's not a bug, but a incomplete feature

**Comment by DaAitch** [comment]
@s1hofmann when I drag red rectangle and release mouse button nothing happens. I'll investigate on this

**Comment by s1hofmann** [comment]
👍 Let me know if you find anything suspicious. I tested various monitor setups, which worked fine for me, but maybe I'm still missing out on something.

**Comment by DaAitch** [comment]
Matching via `desktop.id` seems not to work. Probably it's on linux different than Mac?
image

**Comment by DaAitch** [comment]
On Ubuntu/Linux now everything makes sense. Remember gotomeeting session can only capture one window or all screens, but not only one screen? `desktopCapturer.getSources` always return only one screen which are all screens in one.
We somehow have to detect when this happens (I think it's for `display_id === ''`, can you also check on Mac please?) In this case computation is different.
Another thing is, that the source detection algorithm in the loop may work for `darwin` and/or `windows` platform but not for Linux. We need a switch there, because it seems to be very specific to the system, see https://electronjs.org/docs/api/structures/desktop-capturer-source

**Comment by DaAitch** [comment]
awesome they using different implementations, see https://github.com/electron/electron/issues/12312#issue-305723149
so windows and linux is similiar having only one screen, Mac does a better job.

**Comment by DaAitch** [comment]
@s1hofmann first please check refactoring c1723cd and merge on top of this branch if you like it. Getting rid of callback hell and promise chaining.
Then let's call it `darwin` implementation and I'll provide a Linux impl. Hopefully it also works on Windows then.

**Comment by DaAitch** [comment]
@s1hofmann please check be56923. Hope this will do the trick, at least on my Linux machine with one or two displays it's working. I'll check on Mac now.

**Comment by DaAitch** [comment]
@s1hofmann please check https://github.com/20hoibe/stack/pull/8

**Comment by s1hofmann** [comment]
I'll do as soon as I have a second display at hand. I'll also run tests on a Windows setup.

**Comment by DaAitch** [comment]
Fixed by #8.

**Pull request closed without merging**
